In [1]:
import pandas as pd
import matplotlib.pyplot as plot
%matplotlib inline
import os

In [2]:
os.chdir('C:\\Users\\Admin\\Desktop\\ML\\Cohort 140_Day 41 Dimesnsion Reduction and Cross Validation-20260626T103045Z-3-001\\Cohort 140_Day 41 Dimesnsion Reduction and Cross Validation\\CS 24 Ans -Data Pre-processing-1')
print (os.getcwd())

C:\Users\Admin\Desktop\ML\Cohort 140_Day 41 Dimesnsion Reduction and Cross Validation-20260626T103045Z-3-001\Cohort 140_Day 41 Dimesnsion Reduction and Cross Validation\CS 24 Ans -Data Pre-processing-1

In [3]:
prisoners = pd.read_csv("prisoners.csv")
display (prisoners)

,STATE/UT,YEAR,No. of Inmates benefitted by Elementary Education,No. of Inmates benefitted by Adult Education,No. of Inmates benefitted by Higher Education,No. of Inmates benefitted by Computer Course
0,Andhra Pradesh,2013,9480,13758,672,170
1,Arunachal Pradesh,2013,0,0,0,0
2,Assam,2013,676,750,14,30
3,Bihar,2013,1693,3013,125,1417
4,Chhatisgarh,2013,1664,1803,192,103
5,Goa,2013,7,0,6,88
6,Gujarat,2013,2310,3133,875,966
7,Haryana,2013,1131,774,1112,243
8,Himachal Pradesh,2013,33,80,26,0
9,Jammu & Kashmir,2013,102,124,33,34
10,Jharkhand,2013,3008,2595,138,574
11,Karnataka,2013,633,568,170,12
12,Kerala,2013,156,96,24,250
13,Madhya Pradesh,2013,1978,9574,301,151
14,Maharashtra,2013,346,2743,882,1330
15,Manipur,2013,0,0,0,0
16,Meghalaya,2013,1,30,0,0
17,Mizoram,2013,0,25,18,0
18,Nagaland,2013,0,0,0,0
19,Orissa,2013,622,613,277,384
20,Punjab,2013,325,606,112,168
21,Rajasthan,2013,1050,237,64,38
22,Sikkim,2013,0,0,0,0
23,Tamilnadu,2013,68,1664,757,478
24,Tripura,2013,15,13,4,2
25,Uttar Pradesh,2013,7876,8093,1353,212
26,Uttaranchal,2013,205,42,29,72
27,West Bengal,2013,2023,1889,123,460
28,A & N Islands,2013,167,45,11,0
29,Chandigarh,2013,0,265,85,0
30,D & N Haveli,2013,0,0,0,0
31,Daman & Diu,2013,0,0,0,0
32,Delhi,2013,1458,1187,908,174
33,Lakshadweep,2013,0,0,0,0
34,Pondicherry,2013,0,0,0,0

In [4]:
display (prisoners.head())

,STATE/UT,YEAR,No. of Inmates benefitted by Elementary Education,No. of Inmates benefitted by Adult Education,No. of Inmates benefitted by Higher Education,No. of Inmates benefitted by Computer Course
0,Andhra Pradesh,2013,9480,13758,672,170
1,Arunachal Pradesh,2013,0,0,0,0
2,Assam,2013,676,750,14,30
3,Bihar,2013,1693,3013,125,1417
4,Chhatisgarh,2013,1664,1803,192,103

In [5]:
display (prisoners.tail())

,STATE/UT,YEAR,No. of Inmates benefitted by Elementary Education,No. of Inmates benefitted by Adult Education,No. of Inmates benefitted by Higher Education,No. of Inmates benefitted by Computer Course
30,D & N Haveli,2013,0,0,0,0
31,Daman & Diu,2013,0,0,0,0
32,Delhi,2013,1458,1187,908,174
33,Lakshadweep,2013,0,0,0,0
34,Pondicherry,2013,0,0,0,0

In [6]:
display (prisoners.describe())

,YEAR,No. of Inmates benefitted by Elementary Education,No. of Inmates benefitted by Adult Education,No. of Inmates benefitted by Higher Education,No. of Inmates benefitted by Computer Course
count,35.0,35.000000,35.000000,35.000000,35.000000
mean,2013.0,1057.914286,1534.857143,237.457143,210.171429
std,0.0,2078.196777,3022.110503,375.614191,359.117340
min,2013.0,0.000000,0.000000,0.000000,0.000000
25%,2013.0,0.000000,6.500000,2.000000,0.000000
50%,2013.0,167.000000,237.000000,33.000000,38.000000
75%,2013.0,1294.500000,1733.500000,234.500000,227.500000
max,2013.0,9480.000000,13758.000000,1353.000000,1417.000000

In [7]:
zero_indexes = prisoners.loc[prisoners['No. of Inmates benefitted by Elementary Education']==0]
display  (zero_indexes)

,STATE/UT,YEAR,No. of Inmates benefitted by Elementary Education,No. of Inmates benefitted by Adult Education,No. of Inmates benefitted by Higher Education,No. of Inmates benefitted by Computer Course
1,Arunachal Pradesh,2013,0,0,0,0
15,Manipur,2013,0,0,0,0
17,Mizoram,2013,0,25,18,0
18,Nagaland,2013,0,0,0,0
22,Sikkim,2013,0,0,0,0
29,Chandigarh,2013,0,265,85,0
30,D & N Haveli,2013,0,0,0,0
31,Daman & Diu,2013,0,0,0,0
33,Lakshadweep,2013,0,0,0,0
34,Pondicherry,2013,0,0,0,0

In [8]:
prisoners["Total_Benefited"]=prisoners.iloc[:,2:].sum(axis=1)
display (prisoners)

,STATE/UT,YEAR,No. of Inmates benefitted by Elementary Education,No. of Inmates benefitted by Adult Education,No. of Inmates benefitted by Higher Education,No. of Inmates benefitted by Computer Course,Total_Benefited
0,Andhra Pradesh,2013,9480,13758,672,170,24080
1,Arunachal Pradesh,2013,0,0,0,0,0
2,Assam,2013,676,750,14,30,1470
3,Bihar,2013,1693,3013,125,1417,6248
4,Chhatisgarh,2013,1664,1803,192,103,3762
5,Goa,2013,7,0,6,88,101
6,Gujarat,2013,2310,3133,875,966,7284
7,Haryana,2013,1131,774,1112,243,3260
8,Himachal Pradesh,2013,33,80,26,0,139
9,Jammu & Kashmir,2013,102,124,33,34,293
10,Jharkhand,2013,3008,2595,138,574,6315
11,Karnataka,2013,633,568,170,12,1383
12,Kerala,2013,156,96,24,250,526
13,Madhya Pradesh,2013,1978,9574,301,151,12004
14,Maharashtra,2013,346,2743,882,1330,5301
15,Manipur,2013,0,0,0,0,0
16,Meghalaya,2013,1,30,0,0,31
17,Mizoram,2013,0,25,18,0,43
18,Nagaland,2013,0,0,0,0,0
19,Orissa,2013,622,613,277,384,1896
20,Punjab,2013,325,606,112,168,1211
21,Rajasthan,2013,1050,237,64,38,1389
22,Sikkim,2013,0,0,0,0,0
23,Tamilnadu,2013,68,1664,757,478,2967
24,Tripura,2013,15,13,4,2,34
25,Uttar Pradesh,2013,7876,8093,1353,212,17534
26,Uttaranchal,2013,205,42,29,72,348
27,West Bengal,2013,2023,1889,123,460,4495
28,A & N Islands,2013,167,45,11,0,223
29,Chandigarh,2013,0,265,85,0,350
30,D & N Haveli,2013,0,0,0,0,0
31,Daman & Diu,2013,0,0,0,0,0
32,Delhi,2013,1458,1187,908,174,3727
33,Lakshadweep,2013,0,0,0,0,0
34,Pondicherry,2013,0,0,0,0,0

In [9]:
prisoners_total  =  prisoners
display (prisoners_total)

,STATE/UT,YEAR,No. of Inmates benefitted by Elementary Education,No. of Inmates benefitted by Adult Education,No. of Inmates benefitted by Higher Education,No. of Inmates benefitted by Computer Course,Total_Benefited
0,Andhra Pradesh,2013,9480,13758,672,170,24080
1,Arunachal Pradesh,2013,0,0,0,0,0
2,Assam,2013,676,750,14,30,1470
3,Bihar,2013,1693,3013,125,1417,6248
4,Chhatisgarh,2013,1664,1803,192,103,3762
5,Goa,2013,7,0,6,88,101
6,Gujarat,2013,2310,3133,875,966,7284
7,Haryana,2013,1131,774,1112,243,3260
8,Himachal Pradesh,2013,33,80,26,0,139
9,Jammu & Kashmir,2013,102,124,33,34,293
10,Jharkhand,2013,3008,2595,138,574,6315
11,Karnataka,2013,633,568,170,12,1383
12,Kerala,2013,156,96,24,250,526
13,Madhya Pradesh,2013,1978,9574,301,151,12004
14,Maharashtra,2013,346,2743,882,1330,5301
15,Manipur,2013,0,0,0,0,0
16,Meghalaya,2013,1,30,0,0,31
17,Mizoram,2013,0,25,18,0,43
18,Nagaland,2013,0,0,0,0,0
19,Orissa,2013,622,613,277,384,1896
20,Punjab,2013,325,606,112,168,1211
21,Rajasthan,2013,1050,237,64,38,1389
22,Sikkim,2013,0,0,0,0,0
23,Tamilnadu,2013,68,1664,757,478,2967
24,Tripura,2013,15,13,4,2,34
25,Uttar Pradesh,2013,7876,8093,1353,212,17534
26,Uttaranchal,2013,205,42,29,72,348
27,West Bengal,2013,2023,1889,123,460,4495
28,A & N Islands,2013,167,45,11,0,223
29,Chandigarh,2013,0,265,85,0,350
30,D & N Haveli,2013,0,0,0,0,0
31,Daman & Diu,2013,0,0,0,0,0
32,Delhi,2013,1458,1187,908,174,3727
33,Lakshadweep,2013,0,0,0,0,0
34,Pondicherry,2013,0,0,0,0,0

In [10]:
prisoners_total['YEAR'] =prisoners_total['YEAR'].astype('str')